CREATE SCHEMA IF NOT EXISTS `tsrd`;

CREATE TABLE IF NOT EXISTS `tsrd`.`INSTRUMENT_PRICE_MODIFIER` (
  `id` INT NOT NULL DEFAULT 0,
  `NAME` VARCHAR NOT NULL,
  `modified` NUMERIC(10, 4) NOT NULL,
  PRIMARY KEY (`id`)
)

CREATE INDEX `id_UNIQUE` ON `tsrd`.`INSTRUMENT_PRICE_MODIFIER` (`id` ASC);

CREATE USER IF NOT EXISTS tsrduser PASSWORD 'tsrduser';

GRANT ALL ON SCHEMA tsrd TO tsrduser;
